apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-test
  template:
    metadata:
      labels:
        app: ping-test
    spec:
      containers:
      - name: ping-test
        image: noscopev6/host-test:ip
        ports:
        - containerPort: 8080
