apiVersion: v1
kind: Service
metadata:
  name: ping-test-service
spec:
  selector:
    app: ping-test
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31235 # Specify your desired node port here
  type: NodePort
