version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:3000"
    restart: always
    # environment:
    #   - SMTP_HOST=${SMTP_HOST}
    #   - SMTP_PORT=${SMTP_PORT}
    #   - SMTP_USER=${SMTP_USER}
    #   - SMTP_PASS=${SMTP_PASS}
    #   - MAIL_FROM=${MAIL_FROM}
    #   - MAIL_TO=${MAIL_TO}
    #   - MAIL_SUBJECT=${MAIL_SUBJECT}
